[package]
name = "libp2p-upnp"
edition = "2021"
rust-version = "1.60.0"
description = "UPnP support for libp2p transports"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-trait = "0.1.68"
futures = "0.3.28"
futures-timer = "3.0.2"
igd = { version = "0.12.1", optional = true, features = ["aio"] }
igd_async_std = { version = "0.12.4", optional = true, features = ["aio"] }
libp2p-core = { workspace = true }
libp2p-swarm = { workspace = true }
log = "0.4.19"
void = "1.0.2"

[features]
tokio = ["dep:igd"]
async-std = ["dep:igd_async_std"]

