name: Interoperability Testing
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build-ping-container:
    name: Build Ping interop container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build image
        working-directory: ./test-plans
        run: make
      - name: Upload ping versions info
        uses: actions/upload-artifact@v3
        with:
          name: ping-versions
          path: ./test-plans/ping-versions.json
      - name: Upload image tar
        uses: actions/upload-artifact@v3
        with:
          name: ping-image
          path: ./test-plans/ping-image.tar
  run-multidim-interop:
    name: Run multidimensional interoperability tests
    needs: build-ping-container
    uses: "libp2p/test-plans/.github/workflows/run-testplans.yml@master"
    with:
      dir: "multidim-interop"
      extra-versions: ping-versions
      image-tar: ping-image
      test-filter: "rust-libp2p-head"
